server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.openx.mqtt_subsribe.entity

publish:
  mqtt:
#    host: tcp://localhost:1883
    host: tcp://192.168.31.242:1883
#    username: admin
    username: lzl
#    password: public
    password: lzl123456
    cleansession: false
    clientid: mqtt_subsribe
    default_topic: ??
    timeout: 1000
    keepalive: 10
    connectionTimeout: 3000

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
